name: episode
description: A mobile app to log your TV activity and discover new shows.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  rxdart: "0.27.7"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
